networks:
  1panel-network:
    external: true
services:
  web:
    # Use your custom image instead of the base image
    image: huizhida:latest
    ports:
      - "8078:8080"
    env_file:
      - 1panel.env

  processor:
    image: huizhida:latest
    command: ["php", "/var/www/html/artisan", "conversation:inputs:consume"]
    stop_signal: SIGTERM
    depends_on:
      - web
    env_file:
      - 1panel.env
    deploy:
      replicas: 2  # 可根据负载调整 processor 实例数量

  message-sender:
    image: huizhida:latest
    command: ["php", "/var/www/html/artisan", "conversation:outputs:consume"]
    stop_signal: SIGTERM
    depends_on:
      - web
    env_file:
      - 1panel.env

