services:
  web:
    # Use your custom image instead of the base image
    image: registry.cn-shenzhen.aliyuncs.com/xlankeji/huizhida:latest
    ports:
      - "8078:8080"
    env_file:
      - 1panel.env

  processor:
    image: registry.cn-shenzhen.aliyuncs.com/xlankeji/huizhida:latest
    command: ["php", "/var/www/html/artisan", "processor:consume"]
    stop_signal: SIGTERM
    depends_on:
      - web
    env_file:
      - 1panel.env

  message-sender:
    image: registry.cn-shenzhen.aliyuncs.com/xlankeji/huizhida:latest
    command: ["php", "/var/www/html/artisan", "gateway:message-sender"]
    stop_signal: SIGTERM
    depends_on:
      - web
    env_file:
      - 1panel.env

  transfer-executor:
    image: registry.cn-shenzhen.aliyuncs.com/xlankeji/huizhida:latest
    command: ["php", "/var/www/html/artisan", "gateway:transfer-executor"]
    stop_signal: SIGTERM
    depends_on:
      - web
    env_file:
      - 1panel.env

