networks:
  1panel-network:
    external: true


services:
  web:
    # Use your custom image instead of the base image
    image: huizhida:latest
    networks:
      - 1panel-network
    ports:
      - "8078:8080"
    env_file:
      - 1panel.env
    volumes:
      # 持久化存储目录（上传文件、日志、会话、视图缓存等）
      - ./storage/app:/var/www/html/storage/app
      - ./storage/logs:/var/www/html/storage/logs

  callback:
    image: huizhida:latest
    command: ["php", "/var/www/html/artisan", "huizhida:callback:queue"]
    stop_signal: SIGTERM
    networks:
      - 1panel-network
    depends_on:
      - web
    env_file:
      - 1panel.env
    deploy:
      replicas: 1  # 可根据负载调整 processor 实例数量
    volumes:
      - ./storage/app:/var/www/html/storage/app
      - ./storage/logs:/var/www/html/storage/logs

  inputs:
    image: huizhida:latest
    command: ["php", "/var/www/html/artisan", "huizhida:inputs:queue"]
    stop_signal: SIGTERM
    networks:
      - 1panel-network
    depends_on:
      - web
    env_file:
      - 1panel.env
    deploy:
      replicas: 1  # 可根据负载调整 processor 实例数量
    volumes:
      - ./storage/app:/var/www/html/storage/app
      - ./storage/logs:/var/www/html/storage/logs

  outputs:
    image: huizhida:latest
    command: ["php", "/var/www/html/artisan", "huizhida:outputs:queue"]
    stop_signal: SIGTERM
    networks:
      - 1panel-network
    depends_on:
      - web
    env_file:
      - 1panel.env
    volumes:
      - ./storage/app:/var/www/html/storage/app
      - ./storage/logs:/var/www/html/storage/logs

